FROM microsoft/dotnet:2.2-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["WebAPISample/WebAPISample.csproj", "WebAPISample/"]

RUN dotnet restore "WebAPISample/WebAPISample.csproj"
COPY . .
WORKDIR "/src/WebAPISample"
RUN dotnet build --no-restore "WebAPISample.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]